### ISSUE TITLE
[Docker] docker container 내부에서 사용할 권한 설정

### ISSUE THREAD

**Issue by dimsssss** [connect-foundation/2019-14#178]
- [ ] ~~sudo 명령어를 사용 못하게 설정~~
- [ ] ~~root 계정으로 변경 못하게 설정~~
- [ ] ~~일반 유저 계정을 등록하고 사용~~

~~예시
도커 파일 내부에 해당 명령을 수행하는 쉘스크립트 실행 로직을 추가한다~~

```shell
RUN permission.sh
```

**Comment by DrizzlingCattus** [comment]
토론 결과 차라리 권한을 다 줘서 서버처럼 사용하게하고 우리는 사용량 체크를 해서 제어를 하는 방향이 좋겠다는 의견이 우세

**Comment by DrizzlingCattus** [comment]
- [ ] 네트워크 일정량을 사용하게되면 컨테이너를 종료시킨다.
- [ ] 사용자에게 컨테이너가 종료되었음을 알린다.
