### ISSUE TITLE
[버그] 터미널 지우기가 불편해요

### ISSUE THREAD

**Issue by Einere** [connect-foundation/2019-14#202]
## 해당 버그에 대해서 설명하시오
터미널을 이용한 줄이 여러줄일 때, 터미널을 탈출하려면 일일이 지워줘야 되네요

## 정상적인 동작
단축키나 명령어로 탈출하게 해주세요

## 해당 버그를 재현하기위한 절차를 서술하시오
1. $$$를 처서 터미널로 들어간다
2. 여러 라인을 생성한다.
3. 터미널을 탈출하기 위해 백스페이스를 연타한다.

## 추가 사항
너무 불편해요

**Comment by DrizzlingCattus** [comment]
1. shift + backspace로 지울 수 있게 하였다.

2. ctrl + arrow down으로 터미널 아래에 빈칸이 없어도 포커스 이동할 수 있게 만들었다. (리눅스/윈도우 기준)도

3. 기본 arrow up/down으로 터미널 포커스를 이동할 수 있게 만들었다.
