### ISSUE TITLE
[버그] 명령어인식

### ISSUE THREAD

**Issue by beingPracticer** [connect-foundation/2019-14#203]
## 해당 버그에 대해서 설명하시오
엔터를 2번 눌려야 터미널 결과가 나와요 (윈도우라서 그런가요?)
한줄 전체를 인식하지 못하고 글자가 출력되는 부분만 클릭해야 에디터가 되는 것 같아요

**Comment by DrizzlingCattus** [comment]
Stdin을 입력하는 부분을 삭제하고 터미널처럼 input을 받는 창을 하나만 두어서 엔터 2번을 해야하는 수고로움을 덜게 하였다.
