### ISSUE TITLE
[버그] load 를 한 후에 명령창이 안 먹힙니다!

### ISSUE THREAD

**Issue by kyujonglee** [connect-foundation/2019-14#234]
## 해당 버그에 대해서 설명하시오
터미널 창 명령어가 입력이 안됩니다!

## 정상적인 동작
터미널 창 명령어가 되야합니다!

## 해당 버그를 재현하기위한 절차를 서술하시오
1. $$$로 터미널 창을 연다
2. save를 한다
3. 새로고침 후 load를 한다

**Comment by DrizzlingCattus** [comment]
마우스 이벤트에 있는 버그를 수정하여 load시에도 포커스를 제대로 동작하도록 수정하였다.
