### ISSUE TITLE
[버그] 코드 복사시 첫줄 지우면 CSS 오류 발생

### ISSUE THREAD

**Issue by teihong93** [connect-foundation/2019-14#237]
" ``` "  로 코드 영역을 만든 후 IDE 에서 코드를 복사한 후, 첫번째 줄을 지우면
아래와같이 나타남

<img width="855" alt="스크린샷 2019-12-13 오후 3 23 38" src="https://user-images.githubusercontent.com/52785648/70774125-ab1bbb80-1dbc-11ea-80ef-bb988c211879.png">

**Comment by ImuruKevol** [comment]
저게 아마 웹 기반 IDE에서 코드를 복사하면 저럴건데....

**Comment by ImuruKevol** [comment]
메모
- 붙여넣기 이벤트 발생시 <를 &lt;로 처리하는 것처럼 하면 될 듯 하다
