### ISSUE TITLE
[BUG] 간헐적으로 입력값이 재입력되는 경우

### ISSUE THREAD

**Issue by hzoou** [connect-foundation/2019-14#239]
## 해당 버그에 대해서 설명하시오

간헐적으로 값을 입력하고 엔터를 치니까 맨 끝 글자가 다음 줄에 한번더 입력되는 현상이 발생합니다.
![](https://media.giphy.com/media/H3kyq7c3pxQ1E6h5Lr/giphy.gif)

## 해당 버그를 재현하기위한 절차를 서술하시오

1. '하하'를 입력한 후 엔터를 친다.

**Comment by ImuruKevol** [comment]
이게 브라우저마다 입력 이벤트의 발생 타이밍이 전부 달라서 생기는 문제입니다.
맥북의 고질적인 한글 입력 문제도 포함되어있는 것 같구요.
아마 파이어폭스에서는 문제가 없고, 웨일에서는 글자는 재입력이 안되지만 엔터가 두 번 나오고 크롬에서는 엔터랑 글자가 두 번 다 나올겁니다ㅠㅠㅠㅠㅠ
