### ISSUE TITLE
[에디터 헤더] 에디터 헤더를 표시한다

### ISSUE THREAD

**Issue by RBJH** [connect-foundation/2019-14#31]
- [x] 센터에 문서명을 표시한다.
- [x] 로고를 표시할 수 있다.
- [x] ~~서비스명을 표시할 수 있다.~~
  - 로고에 서비스명이 포함되어 제외

### 에디터 헤더 타이틀
- [x] 헤더의 60%를 차지한다.

### 터미널 아이콘

- [x] 터미널 환경설정 아이콘들을 표시할 수 있다. 
- [x] 우선순위(필수 / 옵션) 순서가 높을 수록 오른쪽으로 출력된다.

### 오류 상황

1. Title이 너무 길어지는 경우 
- > 해더가 가로로 길어져서 보기 싫어진다. 
-> 어떻게 처리할까?
-> 최대 2줄까지만 출력하도록 한다.

**Comment by DrizzlingCattus** [comment]
- [ ] 주석
- [x] 유저 입력 받기
- [x] 헤더 컨테이너
