### ISSUE TITLE
[Editor Tool Bar] 알기 어려운 아이콘에 대한 설명

### ISSUE THREAD

**Issue by dimsssss** [connect-foundation/2019-14#68]
## 토론 대상은?
에디터 툴바 아이콘에 대한 설명을 어떻게 할 것인가

## 왜  토론이 필요한가?
사용자 UX와 관련된 주제라서 다양한 의견이 필요

**Comment by dimsssss** [comment]
한번에 보기 편하게 이미지로 하는게 좋다고 생각해서
개인적으로 설명이 필요하면  **툴팁**으로 넣었으면 합니다.

**Comment by ImuruKevol** [comment]
저도 툴팁으로 표기하면 된다고 생각합니다.
아니면 맨 처음 한 번에 한해서 튜토리얼 이미지같은걸 넣어도 되구요.

**Comment by RBJH** [comment]
튜토리얼 이미지를 보고 깨달았는데 홈페이지에 설명을 적어놓으면 안심이군요!

**Comment by dimsssss** [comment]
설명을 적으면 필요 할 때마다 페이지를 찾아야 하는 번거로움이 있지 않나요?
