### ISSUE TITLE
[Editor Tool Bar] UI 라이브러리 사용 여부 결정

### ISSUE THREAD

**Issue by RBJH** [connect-foundation/2019-14#71]
## 토론 대상은?
UI Library(Bootstrap, Material UI 등) 사용 여부

## 왜  토론이 필요한가?
일관성 있는 코드에 대한 여부

## 토론을 위한 래퍼런스
전반적인 기능 외적인 css 디자인 부분에 대한 생산성과 학습 부분에 대한 우선순위에 따라 결정

**Comment by DrizzlingCattus** [comment]
우리가 커스텀할 수 있는 pure css를 사용하자는 의견으로 수렴.

다만 이미 디자이너들이 뽑아둔 색상 테마를 사용해서 스타일을 통일시키는데 도움을 받자는쪽으로 결정.
