### ISSUE TITLE
[Issue] Issue #3에 대한 구체적인 사항 논의 필요

### ISSUE THREAD

**Issue by RBJH** [connect-foundation/2019-14#91]
## 토론 대상은?
Issues #3 

## 왜  토론이 필요한가?
중간 데모까지 구현할 부분 체크리스트 터미널 명령어 지원 범위 구체화 필요

**Comment by DrizzlingCattus** [comment]
![boostwriter](https://user-images.githubusercontent.com/4661295/69347898-a2056600-0cb8-11ea-8da2-8c706a6c16b1.jpg)

**Comment by DrizzlingCattus** [comment]
![boostwriter(1)](https://user-images.githubusercontent.com/4661295/69349455-1b9e5380-0cbb-11ea-8f7b-98b71e443f2d.jpg)

**Comment by DrizzlingCattus** [comment]
![boostwriter_resize2](https://user-images.githubusercontent.com/4661295/69394024-2c33e580-0d1e-11ea-8c7a-49cec33aeea7.jpg)

**Comment by DrizzlingCattus** [comment]
데모 시나리오를 작성하여 이에 필요한 내용을 구체화시킴
